### ISSUE TITLE
Error in pre_processing.py

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/maternal_health_risk_predictor#13]
I think there's an error in the way the data was split into train and test - it may have included the column names as one of the rows. Inside of `data/processed/train_df.csv` [link](https://github.com/UBC-MDS/maternal_health_risk_predictor/blob/main/data/processed/train_df.csv), row `319` has the names of the columns in the original dataset. 

@lennonay

**Comment by lennonay** [comment]
Yes indeed, it was an error with the download_data.py script, it should be fixed now
